version: '3.3'

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - '5432:5432'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
