export enum ConfigEnum {
  PORT = 'PORT',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DB = 'POSTGRES_DB',
  POSTGRES_PORT = 'POSTGRES_PORT',
  JWT_SECRET = 'JWT_SECRET',
}
